language: php
php:
  - '7.1'
  - '7.2'
  - nightly

services:
  - docker

addons:
  hosts:
    - security.sensiolabs.org

before_install:
  - docker pull nginx:alpine
  - docker run -v $(pwd)/.travis/nginx.conf:/etc/nginx/nginx.conf:ro -d -p 80:80 nginx:alpine

install:
   - composer install

script:
    - ./bin/phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/phpstan analyse --level=7 src

after_success:
  - bash <(curl -s https://codecov.io/bash)
